// Code generated by ent, DO NOT EDIT.

package luminatask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldTaskID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldAccountID, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// TaskType applies equality check predicate on the "task_type" field. It's identical to TaskTypeEQ.
func TaskType(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldTaskType, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldModel, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldStatus, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldCompletedAt, v))
}

// UserDeletedAt applies equality check predicate on the "user_deleted_at" field. It's identical to UserDeletedAtEQ.
func UserDeletedAt(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUserDeletedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldTaskID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldGroupID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldAccountID, v))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// TaskTypeEQ applies the EQ predicate on the "task_type" field.
func TaskTypeEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldTaskType, v))
}

// TaskTypeNEQ applies the NEQ predicate on the "task_type" field.
func TaskTypeNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldTaskType, v))
}

// TaskTypeIn applies the In predicate on the "task_type" field.
func TaskTypeIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldTaskType, vs...))
}

// TaskTypeNotIn applies the NotIn predicate on the "task_type" field.
func TaskTypeNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldTaskType, vs...))
}

// TaskTypeGT applies the GT predicate on the "task_type" field.
func TaskTypeGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldTaskType, v))
}

// TaskTypeGTE applies the GTE predicate on the "task_type" field.
func TaskTypeGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldTaskType, v))
}

// TaskTypeLT applies the LT predicate on the "task_type" field.
func TaskTypeLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldTaskType, v))
}

// TaskTypeLTE applies the LTE predicate on the "task_type" field.
func TaskTypeLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldTaskType, v))
}

// TaskTypeContains applies the Contains predicate on the "task_type" field.
func TaskTypeContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldTaskType, v))
}

// TaskTypeHasPrefix applies the HasPrefix predicate on the "task_type" field.
func TaskTypeHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldTaskType, v))
}

// TaskTypeHasSuffix applies the HasSuffix predicate on the "task_type" field.
func TaskTypeHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldTaskType, v))
}

// TaskTypeEqualFold applies the EqualFold predicate on the "task_type" field.
func TaskTypeEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldTaskType, v))
}

// TaskTypeContainsFold applies the ContainsFold predicate on the "task_type" field.
func TaskTypeContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldTaskType, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldModel, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotNull(FieldCompletedAt))
}

// UserDeletedAtEQ applies the EQ predicate on the "user_deleted_at" field.
func UserDeletedAtEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldEQ(FieldUserDeletedAt, v))
}

// UserDeletedAtNEQ applies the NEQ predicate on the "user_deleted_at" field.
func UserDeletedAtNEQ(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNEQ(FieldUserDeletedAt, v))
}

// UserDeletedAtIn applies the In predicate on the "user_deleted_at" field.
func UserDeletedAtIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIn(FieldUserDeletedAt, vs...))
}

// UserDeletedAtNotIn applies the NotIn predicate on the "user_deleted_at" field.
func UserDeletedAtNotIn(vs ...time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotIn(FieldUserDeletedAt, vs...))
}

// UserDeletedAtGT applies the GT predicate on the "user_deleted_at" field.
func UserDeletedAtGT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGT(FieldUserDeletedAt, v))
}

// UserDeletedAtGTE applies the GTE predicate on the "user_deleted_at" field.
func UserDeletedAtGTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldGTE(FieldUserDeletedAt, v))
}

// UserDeletedAtLT applies the LT predicate on the "user_deleted_at" field.
func UserDeletedAtLT(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLT(FieldUserDeletedAt, v))
}

// UserDeletedAtLTE applies the LTE predicate on the "user_deleted_at" field.
func UserDeletedAtLTE(v time.Time) predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldLTE(FieldUserDeletedAt, v))
}

// UserDeletedAtIsNil applies the IsNil predicate on the "user_deleted_at" field.
func UserDeletedAtIsNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldIsNull(FieldUserDeletedAt))
}

// UserDeletedAtNotNil applies the NotNil predicate on the "user_deleted_at" field.
func UserDeletedAtNotNil() predicate.LuminaTask {
	return predicate.LuminaTask(sql.FieldNotNull(FieldUserDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LuminaTask) predicate.LuminaTask {
	return predicate.LuminaTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LuminaTask) predicate.LuminaTask {
	return predicate.LuminaTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LuminaTask) predicate.LuminaTask {
	return predicate.LuminaTask(sql.NotPredicates(p))
}
