// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/luminatask"
)

// LuminaTask is the model entity for the LuminaTask schema.
type LuminaTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID string `json:"upstream_task_id,omitempty"`
	// TaskType holds the value of the "task_type" field.
	TaskType string `json:"task_type,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RequestPayload holds the value of the "request_payload" field.
	RequestPayload map[string]interface{} `json:"request_payload,omitempty"`
	// ResponsePayload holds the value of the "response_payload" field.
	ResponsePayload map[string]interface{} `json:"response_payload,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// UserDeletedAt holds the value of the "user_deleted_at" field.
	UserDeletedAt *time.Time `json:"user_deleted_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LuminaTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case luminatask.FieldRequestPayload, luminatask.FieldResponsePayload:
			values[i] = new([]byte)
		case luminatask.FieldID, luminatask.FieldUserID, luminatask.FieldAPIKeyID, luminatask.FieldGroupID, luminatask.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case luminatask.FieldTaskID, luminatask.FieldUpstreamTaskID, luminatask.FieldTaskType, luminatask.FieldModel, luminatask.FieldStatus, luminatask.FieldErrorCode, luminatask.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case luminatask.FieldCreatedAt, luminatask.FieldUpdatedAt, luminatask.FieldCompletedAt, luminatask.FieldUserDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LuminaTask fields.
func (_m *LuminaTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case luminatask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case luminatask.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case luminatask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case luminatask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case luminatask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case luminatask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case luminatask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = value.String
			}
		case luminatask.FieldTaskType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_type", values[i])
			} else if value.Valid {
				_m.TaskType = value.String
			}
		case luminatask.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case luminatask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case luminatask.FieldRequestPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestPayload); err != nil {
					return fmt.Errorf("unmarshal field request_payload: %w", err)
				}
			}
		case luminatask.FieldResponsePayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponsePayload); err != nil {
					return fmt.Errorf("unmarshal field response_payload: %w", err)
				}
			}
		case luminatask.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case luminatask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case luminatask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case luminatask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case luminatask.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case luminatask.FieldUserDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field user_deleted_at", values[i])
			} else if value.Valid {
				_m.UserDeletedAt = new(time.Time)
				*_m.UserDeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LuminaTask.
// This includes values selected through modifiers, order, etc.
func (_m *LuminaTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LuminaTask.
// Note that you need to call LuminaTask.Unwrap() before calling this method if this LuminaTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LuminaTask) Update() *LuminaTaskUpdateOne {
	return NewLuminaTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LuminaTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LuminaTask) Unwrap() *LuminaTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LuminaTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LuminaTask) String() string {
	var builder strings.Builder
	builder.WriteString("LuminaTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("upstream_task_id=")
	builder.WriteString(_m.UpstreamTaskID)
	builder.WriteString(", ")
	builder.WriteString("task_type=")
	builder.WriteString(_m.TaskType)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("request_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestPayload))
	builder.WriteString(", ")
	builder.WriteString("response_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponsePayload))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UserDeletedAt; v != nil {
		builder.WriteString("user_deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// LuminaTasks is a parsable slice of LuminaTask.
type LuminaTasks []*LuminaTask
