// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/luminatask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LuminaTaskUpdate is the builder for updating LuminaTask entities.
type LuminaTaskUpdate struct {
	config
	hooks    []Hook
	mutation *LuminaTaskMutation
}

// Where appends a list predicates to the LuminaTaskUpdate builder.
func (_u *LuminaTaskUpdate) Where(ps ...predicate.LuminaTask) *LuminaTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LuminaTaskUpdate) SetUserID(v int64) *LuminaTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableUserID(v *int64) *LuminaTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LuminaTaskUpdate) AddUserID(v int64) *LuminaTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *LuminaTaskUpdate) SetAPIKeyID(v int64) *LuminaTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableAPIKeyID(v *int64) *LuminaTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *LuminaTaskUpdate) AddAPIKeyID(v int64) *LuminaTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *LuminaTaskUpdate) SetGroupID(v int64) *LuminaTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableGroupID(v *int64) *LuminaTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *LuminaTaskUpdate) AddGroupID(v int64) *LuminaTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *LuminaTaskUpdate) SetAccountID(v int64) *LuminaTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableAccountID(v *int64) *LuminaTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *LuminaTaskUpdate) AddAccountID(v int64) *LuminaTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *LuminaTaskUpdate) SetUpstreamTaskID(v string) *LuminaTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableUpstreamTaskID(v *string) *LuminaTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *LuminaTaskUpdate) SetTaskType(v string) *LuminaTaskUpdate {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableTaskType(v *string) *LuminaTaskUpdate {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *LuminaTaskUpdate) SetModel(v string) *LuminaTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableModel(v *string) *LuminaTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LuminaTaskUpdate) SetStatus(v string) *LuminaTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableStatus(v *string) *LuminaTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRequestPayload sets the "request_payload" field.
func (_u *LuminaTaskUpdate) SetRequestPayload(v map[string]interface{}) *LuminaTaskUpdate {
	_u.mutation.SetRequestPayload(v)
	return _u
}

// SetResponsePayload sets the "response_payload" field.
func (_u *LuminaTaskUpdate) SetResponsePayload(v map[string]interface{}) *LuminaTaskUpdate {
	_u.mutation.SetResponsePayload(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *LuminaTaskUpdate) SetErrorCode(v string) *LuminaTaskUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableErrorCode(v *string) *LuminaTaskUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *LuminaTaskUpdate) ClearErrorCode() *LuminaTaskUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *LuminaTaskUpdate) SetErrorMessage(v string) *LuminaTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableErrorMessage(v *string) *LuminaTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *LuminaTaskUpdate) ClearErrorMessage() *LuminaTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LuminaTaskUpdate) SetUpdatedAt(v time.Time) *LuminaTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *LuminaTaskUpdate) SetCompletedAt(v time.Time) *LuminaTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableCompletedAt(v *time.Time) *LuminaTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *LuminaTaskUpdate) ClearCompletedAt() *LuminaTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (_u *LuminaTaskUpdate) SetUserDeletedAt(v time.Time) *LuminaTaskUpdate {
	_u.mutation.SetUserDeletedAt(v)
	return _u
}

// SetNillableUserDeletedAt sets the "user_deleted_at" field if the given value is not nil.
func (_u *LuminaTaskUpdate) SetNillableUserDeletedAt(v *time.Time) *LuminaTaskUpdate {
	if v != nil {
		_u.SetUserDeletedAt(*v)
	}
	return _u
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (_u *LuminaTaskUpdate) ClearUserDeletedAt() *LuminaTaskUpdate {
	_u.mutation.ClearUserDeletedAt()
	return _u
}

// Mutation returns the LuminaTaskMutation object of the builder.
func (_u *LuminaTaskUpdate) Mutation() *LuminaTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LuminaTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LuminaTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LuminaTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LuminaTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LuminaTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := luminatask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LuminaTaskUpdate) check() error {
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := luminatask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskType(); ok {
		if err := luminatask.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := luminatask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := luminatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := luminatask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *LuminaTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(luminatask.Table, luminatask.Columns, sqlgraph.NewFieldSpec(luminatask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(luminatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(luminatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(luminatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(luminatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(luminatask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(luminatask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(luminatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(luminatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(luminatask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(luminatask.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(luminatask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(luminatask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPayload(); ok {
		_spec.SetField(luminatask.FieldRequestPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ResponsePayload(); ok {
		_spec.SetField(luminatask.FieldResponsePayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(luminatask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(luminatask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(luminatask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(luminatask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(luminatask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(luminatask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(luminatask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserDeletedAt(); ok {
		_spec.SetField(luminatask.FieldUserDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.UserDeletedAtCleared() {
		_spec.ClearField(luminatask.FieldUserDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{luminatask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LuminaTaskUpdateOne is the builder for updating a single LuminaTask entity.
type LuminaTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LuminaTaskMutation
}

// SetUserID sets the "user_id" field.
func (_u *LuminaTaskUpdateOne) SetUserID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableUserID(v *int64) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LuminaTaskUpdateOne) AddUserID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *LuminaTaskUpdateOne) SetAPIKeyID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableAPIKeyID(v *int64) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *LuminaTaskUpdateOne) AddAPIKeyID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *LuminaTaskUpdateOne) SetGroupID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableGroupID(v *int64) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *LuminaTaskUpdateOne) AddGroupID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *LuminaTaskUpdateOne) SetAccountID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableAccountID(v *int64) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *LuminaTaskUpdateOne) AddAccountID(v int64) *LuminaTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *LuminaTaskUpdateOne) SetUpstreamTaskID(v string) *LuminaTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *LuminaTaskUpdateOne) SetTaskType(v string) *LuminaTaskUpdateOne {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableTaskType(v *string) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *LuminaTaskUpdateOne) SetModel(v string) *LuminaTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableModel(v *string) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LuminaTaskUpdateOne) SetStatus(v string) *LuminaTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableStatus(v *string) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRequestPayload sets the "request_payload" field.
func (_u *LuminaTaskUpdateOne) SetRequestPayload(v map[string]interface{}) *LuminaTaskUpdateOne {
	_u.mutation.SetRequestPayload(v)
	return _u
}

// SetResponsePayload sets the "response_payload" field.
func (_u *LuminaTaskUpdateOne) SetResponsePayload(v map[string]interface{}) *LuminaTaskUpdateOne {
	_u.mutation.SetResponsePayload(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *LuminaTaskUpdateOne) SetErrorCode(v string) *LuminaTaskUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableErrorCode(v *string) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *LuminaTaskUpdateOne) ClearErrorCode() *LuminaTaskUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *LuminaTaskUpdateOne) SetErrorMessage(v string) *LuminaTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableErrorMessage(v *string) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *LuminaTaskUpdateOne) ClearErrorMessage() *LuminaTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LuminaTaskUpdateOne) SetUpdatedAt(v time.Time) *LuminaTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *LuminaTaskUpdateOne) SetCompletedAt(v time.Time) *LuminaTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *LuminaTaskUpdateOne) ClearCompletedAt() *LuminaTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (_u *LuminaTaskUpdateOne) SetUserDeletedAt(v time.Time) *LuminaTaskUpdateOne {
	_u.mutation.SetUserDeletedAt(v)
	return _u
}

// SetNillableUserDeletedAt sets the "user_deleted_at" field if the given value is not nil.
func (_u *LuminaTaskUpdateOne) SetNillableUserDeletedAt(v *time.Time) *LuminaTaskUpdateOne {
	if v != nil {
		_u.SetUserDeletedAt(*v)
	}
	return _u
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (_u *LuminaTaskUpdateOne) ClearUserDeletedAt() *LuminaTaskUpdateOne {
	_u.mutation.ClearUserDeletedAt()
	return _u
}

// Mutation returns the LuminaTaskMutation object of the builder.
func (_u *LuminaTaskUpdateOne) Mutation() *LuminaTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the LuminaTaskUpdate builder.
func (_u *LuminaTaskUpdateOne) Where(ps ...predicate.LuminaTask) *LuminaTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LuminaTaskUpdateOne) Select(field string, fields ...string) *LuminaTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LuminaTask entity.
func (_u *LuminaTaskUpdateOne) Save(ctx context.Context) (*LuminaTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LuminaTaskUpdateOne) SaveX(ctx context.Context) *LuminaTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LuminaTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LuminaTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LuminaTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := luminatask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LuminaTaskUpdateOne) check() error {
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := luminatask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskType(); ok {
		if err := luminatask.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := luminatask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := luminatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := luminatask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *LuminaTaskUpdateOne) sqlSave(ctx context.Context) (_node *LuminaTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(luminatask.Table, luminatask.Columns, sqlgraph.NewFieldSpec(luminatask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LuminaTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, luminatask.FieldID)
		for _, f := range fields {
			if !luminatask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != luminatask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(luminatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(luminatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(luminatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(luminatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(luminatask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(luminatask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(luminatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(luminatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(luminatask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(luminatask.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(luminatask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(luminatask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPayload(); ok {
		_spec.SetField(luminatask.FieldRequestPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ResponsePayload(); ok {
		_spec.SetField(luminatask.FieldResponsePayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(luminatask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(luminatask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(luminatask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(luminatask.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(luminatask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(luminatask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(luminatask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserDeletedAt(); ok {
		_spec.SetField(luminatask.FieldUserDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.UserDeletedAtCleared() {
		_spec.ClearField(luminatask.FieldUserDeletedAt, field.TypeTime)
	}
	_node = &LuminaTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{luminatask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
