// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/luminatask"
)

// LuminaTaskCreate is the builder for creating a LuminaTask entity.
type LuminaTaskCreate struct {
	config
	mutation *LuminaTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskID sets the "task_id" field.
func (_c *LuminaTaskCreate) SetTaskID(v string) *LuminaTaskCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LuminaTaskCreate) SetUserID(v int64) *LuminaTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *LuminaTaskCreate) SetAPIKeyID(v int64) *LuminaTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *LuminaTaskCreate) SetGroupID(v int64) *LuminaTaskCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *LuminaTaskCreate) SetAccountID(v int64) *LuminaTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *LuminaTaskCreate) SetUpstreamTaskID(v string) *LuminaTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetTaskType sets the "task_type" field.
func (_c *LuminaTaskCreate) SetTaskType(v string) *LuminaTaskCreate {
	_c.mutation.SetTaskType(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *LuminaTaskCreate) SetModel(v string) *LuminaTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LuminaTaskCreate) SetStatus(v string) *LuminaTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableStatus(v *string) *LuminaTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRequestPayload sets the "request_payload" field.
func (_c *LuminaTaskCreate) SetRequestPayload(v map[string]interface{}) *LuminaTaskCreate {
	_c.mutation.SetRequestPayload(v)
	return _c
}

// SetResponsePayload sets the "response_payload" field.
func (_c *LuminaTaskCreate) SetResponsePayload(v map[string]interface{}) *LuminaTaskCreate {
	_c.mutation.SetResponsePayload(v)
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *LuminaTaskCreate) SetErrorCode(v string) *LuminaTaskCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableErrorCode(v *string) *LuminaTaskCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *LuminaTaskCreate) SetErrorMessage(v string) *LuminaTaskCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableErrorMessage(v *string) *LuminaTaskCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LuminaTaskCreate) SetCreatedAt(v time.Time) *LuminaTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableCreatedAt(v *time.Time) *LuminaTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LuminaTaskCreate) SetUpdatedAt(v time.Time) *LuminaTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableUpdatedAt(v *time.Time) *LuminaTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *LuminaTaskCreate) SetCompletedAt(v time.Time) *LuminaTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableCompletedAt(v *time.Time) *LuminaTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (_c *LuminaTaskCreate) SetUserDeletedAt(v time.Time) *LuminaTaskCreate {
	_c.mutation.SetUserDeletedAt(v)
	return _c
}

// SetNillableUserDeletedAt sets the "user_deleted_at" field if the given value is not nil.
func (_c *LuminaTaskCreate) SetNillableUserDeletedAt(v *time.Time) *LuminaTaskCreate {
	if v != nil {
		_c.SetUserDeletedAt(*v)
	}
	return _c
}

// Mutation returns the LuminaTaskMutation object of the builder.
func (_c *LuminaTaskCreate) Mutation() *LuminaTaskMutation {
	return _c.mutation
}

// Save creates the LuminaTask in the database.
func (_c *LuminaTaskCreate) Save(ctx context.Context) (*LuminaTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LuminaTaskCreate) SaveX(ctx context.Context) *LuminaTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LuminaTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LuminaTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LuminaTaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := luminatask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RequestPayload(); !ok {
		v := luminatask.DefaultRequestPayload()
		_c.mutation.SetRequestPayload(v)
	}
	if _, ok := _c.mutation.ResponsePayload(); !ok {
		v := luminatask.DefaultResponsePayload()
		_c.mutation.SetResponsePayload(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := luminatask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := luminatask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LuminaTaskCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "LuminaTask.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := luminatask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LuminaTask.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "LuminaTask.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "LuminaTask.group_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "LuminaTask.account_id"`)}
	}
	if _, ok := _c.mutation.UpstreamTaskID(); !ok {
		return &ValidationError{Name: "upstream_task_id", err: errors.New(`ent: missing required field "LuminaTask.upstream_task_id"`)}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := luminatask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.upstream_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "LuminaTask.task_type"`)}
	}
	if v, ok := _c.mutation.TaskType(); ok {
		if err := luminatask.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.task_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "LuminaTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := luminatask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LuminaTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := luminatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestPayload(); !ok {
		return &ValidationError{Name: "request_payload", err: errors.New(`ent: missing required field "LuminaTask.request_payload"`)}
	}
	if _, ok := _c.mutation.ResponsePayload(); !ok {
		return &ValidationError{Name: "response_payload", err: errors.New(`ent: missing required field "LuminaTask.response_payload"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := luminatask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "LuminaTask.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LuminaTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LuminaTask.updated_at"`)}
	}
	return nil
}

func (_c *LuminaTaskCreate) sqlSave(ctx context.Context) (*LuminaTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LuminaTaskCreate) createSpec() (*LuminaTask, *sqlgraph.CreateSpec) {
	var (
		_node = &LuminaTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(luminatask.Table, sqlgraph.NewFieldSpec(luminatask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(luminatask.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(luminatask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(luminatask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(luminatask.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(luminatask.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(luminatask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = value
	}
	if value, ok := _c.mutation.TaskType(); ok {
		_spec.SetField(luminatask.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(luminatask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(luminatask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestPayload(); ok {
		_spec.SetField(luminatask.FieldRequestPayload, field.TypeJSON, value)
		_node.RequestPayload = value
	}
	if value, ok := _c.mutation.ResponsePayload(); ok {
		_spec.SetField(luminatask.FieldResponsePayload, field.TypeJSON, value)
		_node.ResponsePayload = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(luminatask.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(luminatask.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(luminatask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(luminatask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(luminatask.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.UserDeletedAt(); ok {
		_spec.SetField(luminatask.FieldUserDeletedAt, field.TypeTime, value)
		_node.UserDeletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LuminaTask.Create().
//		SetTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LuminaTaskUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *LuminaTaskCreate) OnConflict(opts ...sql.ConflictOption) *LuminaTaskUpsertOne {
	_c.conflict = opts
	return &LuminaTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LuminaTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LuminaTaskCreate) OnConflictColumns(columns ...string) *LuminaTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LuminaTaskUpsertOne{
		create: _c,
	}
}

type (
	// LuminaTaskUpsertOne is the builder for "upsert"-ing
	//  one LuminaTask node.
	LuminaTaskUpsertOne struct {
		create *LuminaTaskCreate
	}

	// LuminaTaskUpsert is the "OnConflict" setter.
	LuminaTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *LuminaTaskUpsert) SetUserID(v int64) *LuminaTaskUpsert {
	u.Set(luminatask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateUserID() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LuminaTaskUpsert) AddUserID(v int64) *LuminaTaskUpsert {
	u.Add(luminatask.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LuminaTaskUpsert) SetAPIKeyID(v int64) *LuminaTaskUpsert {
	u.Set(luminatask.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateAPIKeyID() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LuminaTaskUpsert) AddAPIKeyID(v int64) *LuminaTaskUpsert {
	u.Add(luminatask.FieldAPIKeyID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *LuminaTaskUpsert) SetGroupID(v int64) *LuminaTaskUpsert {
	u.Set(luminatask.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateGroupID() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *LuminaTaskUpsert) AddGroupID(v int64) *LuminaTaskUpsert {
	u.Add(luminatask.FieldGroupID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *LuminaTaskUpsert) SetAccountID(v int64) *LuminaTaskUpsert {
	u.Set(luminatask.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateAccountID() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *LuminaTaskUpsert) AddAccountID(v int64) *LuminaTaskUpsert {
	u.Add(luminatask.FieldAccountID, v)
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *LuminaTaskUpsert) SetUpstreamTaskID(v string) *LuminaTaskUpsert {
	u.Set(luminatask.FieldUpstreamTaskID, v)
	return u
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateUpstreamTaskID() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldUpstreamTaskID)
	return u
}

// SetTaskType sets the "task_type" field.
func (u *LuminaTaskUpsert) SetTaskType(v string) *LuminaTaskUpsert {
	u.Set(luminatask.FieldTaskType, v)
	return u
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateTaskType() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldTaskType)
	return u
}

// SetModel sets the "model" field.
func (u *LuminaTaskUpsert) SetModel(v string) *LuminaTaskUpsert {
	u.Set(luminatask.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateModel() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldModel)
	return u
}

// SetStatus sets the "status" field.
func (u *LuminaTaskUpsert) SetStatus(v string) *LuminaTaskUpsert {
	u.Set(luminatask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateStatus() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldStatus)
	return u
}

// SetRequestPayload sets the "request_payload" field.
func (u *LuminaTaskUpsert) SetRequestPayload(v map[string]interface{}) *LuminaTaskUpsert {
	u.Set(luminatask.FieldRequestPayload, v)
	return u
}

// UpdateRequestPayload sets the "request_payload" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateRequestPayload() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldRequestPayload)
	return u
}

// SetResponsePayload sets the "response_payload" field.
func (u *LuminaTaskUpsert) SetResponsePayload(v map[string]interface{}) *LuminaTaskUpsert {
	u.Set(luminatask.FieldResponsePayload, v)
	return u
}

// UpdateResponsePayload sets the "response_payload" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateResponsePayload() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldResponsePayload)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *LuminaTaskUpsert) SetErrorCode(v string) *LuminaTaskUpsert {
	u.Set(luminatask.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateErrorCode() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *LuminaTaskUpsert) ClearErrorCode() *LuminaTaskUpsert {
	u.SetNull(luminatask.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *LuminaTaskUpsert) SetErrorMessage(v string) *LuminaTaskUpsert {
	u.Set(luminatask.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateErrorMessage() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *LuminaTaskUpsert) ClearErrorMessage() *LuminaTaskUpsert {
	u.SetNull(luminatask.FieldErrorMessage)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LuminaTaskUpsert) SetUpdatedAt(v time.Time) *LuminaTaskUpsert {
	u.Set(luminatask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateUpdatedAt() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldUpdatedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *LuminaTaskUpsert) SetCompletedAt(v time.Time) *LuminaTaskUpsert {
	u.Set(luminatask.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateCompletedAt() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *LuminaTaskUpsert) ClearCompletedAt() *LuminaTaskUpsert {
	u.SetNull(luminatask.FieldCompletedAt)
	return u
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (u *LuminaTaskUpsert) SetUserDeletedAt(v time.Time) *LuminaTaskUpsert {
	u.Set(luminatask.FieldUserDeletedAt, v)
	return u
}

// UpdateUserDeletedAt sets the "user_deleted_at" field to the value that was provided on create.
func (u *LuminaTaskUpsert) UpdateUserDeletedAt() *LuminaTaskUpsert {
	u.SetExcluded(luminatask.FieldUserDeletedAt)
	return u
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (u *LuminaTaskUpsert) ClearUserDeletedAt() *LuminaTaskUpsert {
	u.SetNull(luminatask.FieldUserDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LuminaTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LuminaTaskUpsertOne) UpdateNewValues() *LuminaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TaskID(); exists {
			s.SetIgnore(luminatask.FieldTaskID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(luminatask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LuminaTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LuminaTaskUpsertOne) Ignore() *LuminaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LuminaTaskUpsertOne) DoNothing() *LuminaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LuminaTaskCreate.OnConflict
// documentation for more info.
func (u *LuminaTaskUpsertOne) Update(set func(*LuminaTaskUpsert)) *LuminaTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LuminaTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LuminaTaskUpsertOne) SetUserID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LuminaTaskUpsertOne) AddUserID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateUserID() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LuminaTaskUpsertOne) SetAPIKeyID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LuminaTaskUpsertOne) AddAPIKeyID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateAPIKeyID() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *LuminaTaskUpsertOne) SetGroupID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *LuminaTaskUpsertOne) AddGroupID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateGroupID() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *LuminaTaskUpsertOne) SetAccountID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *LuminaTaskUpsertOne) AddAccountID(v int64) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateAccountID() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *LuminaTaskUpsertOne) SetUpstreamTaskID(v string) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateUpstreamTaskID() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// SetTaskType sets the "task_type" field.
func (u *LuminaTaskUpsertOne) SetTaskType(v string) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetTaskType(v)
	})
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateTaskType() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateTaskType()
	})
}

// SetModel sets the "model" field.
func (u *LuminaTaskUpsertOne) SetModel(v string) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateModel() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateModel()
	})
}

// SetStatus sets the "status" field.
func (u *LuminaTaskUpsertOne) SetStatus(v string) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateStatus() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestPayload sets the "request_payload" field.
func (u *LuminaTaskUpsertOne) SetRequestPayload(v map[string]interface{}) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetRequestPayload(v)
	})
}

// UpdateRequestPayload sets the "request_payload" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateRequestPayload() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateRequestPayload()
	})
}

// SetResponsePayload sets the "response_payload" field.
func (u *LuminaTaskUpsertOne) SetResponsePayload(v map[string]interface{}) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetResponsePayload(v)
	})
}

// UpdateResponsePayload sets the "response_payload" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateResponsePayload() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateResponsePayload()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *LuminaTaskUpsertOne) SetErrorCode(v string) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateErrorCode() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *LuminaTaskUpsertOne) ClearErrorCode() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *LuminaTaskUpsertOne) SetErrorMessage(v string) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateErrorMessage() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *LuminaTaskUpsertOne) ClearErrorMessage() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LuminaTaskUpsertOne) SetUpdatedAt(v time.Time) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateUpdatedAt() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *LuminaTaskUpsertOne) SetCompletedAt(v time.Time) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateCompletedAt() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *LuminaTaskUpsertOne) ClearCompletedAt() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (u *LuminaTaskUpsertOne) SetUserDeletedAt(v time.Time) *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUserDeletedAt(v)
	})
}

// UpdateUserDeletedAt sets the "user_deleted_at" field to the value that was provided on create.
func (u *LuminaTaskUpsertOne) UpdateUserDeletedAt() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUserDeletedAt()
	})
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (u *LuminaTaskUpsertOne) ClearUserDeletedAt() *LuminaTaskUpsertOne {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearUserDeletedAt()
	})
}

// Exec executes the query.
func (u *LuminaTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LuminaTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LuminaTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LuminaTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LuminaTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LuminaTaskCreateBulk is the builder for creating many LuminaTask entities in bulk.
type LuminaTaskCreateBulk struct {
	config
	err      error
	builders []*LuminaTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the LuminaTask entities in the database.
func (_c *LuminaTaskCreateBulk) Save(ctx context.Context) ([]*LuminaTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LuminaTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LuminaTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LuminaTaskCreateBulk) SaveX(ctx context.Context) []*LuminaTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LuminaTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LuminaTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LuminaTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LuminaTaskUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *LuminaTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *LuminaTaskUpsertBulk {
	_c.conflict = opts
	return &LuminaTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LuminaTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LuminaTaskCreateBulk) OnConflictColumns(columns ...string) *LuminaTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LuminaTaskUpsertBulk{
		create: _c,
	}
}

// LuminaTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of LuminaTask nodes.
type LuminaTaskUpsertBulk struct {
	create *LuminaTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LuminaTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LuminaTaskUpsertBulk) UpdateNewValues() *LuminaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TaskID(); exists {
				s.SetIgnore(luminatask.FieldTaskID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(luminatask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LuminaTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LuminaTaskUpsertBulk) Ignore() *LuminaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LuminaTaskUpsertBulk) DoNothing() *LuminaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LuminaTaskCreateBulk.OnConflict
// documentation for more info.
func (u *LuminaTaskUpsertBulk) Update(set func(*LuminaTaskUpsert)) *LuminaTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LuminaTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LuminaTaskUpsertBulk) SetUserID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LuminaTaskUpsertBulk) AddUserID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateUserID() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LuminaTaskUpsertBulk) SetAPIKeyID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LuminaTaskUpsertBulk) AddAPIKeyID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateAPIKeyID() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *LuminaTaskUpsertBulk) SetGroupID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *LuminaTaskUpsertBulk) AddGroupID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateGroupID() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *LuminaTaskUpsertBulk) SetAccountID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *LuminaTaskUpsertBulk) AddAccountID(v int64) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateAccountID() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *LuminaTaskUpsertBulk) SetUpstreamTaskID(v string) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateUpstreamTaskID() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// SetTaskType sets the "task_type" field.
func (u *LuminaTaskUpsertBulk) SetTaskType(v string) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetTaskType(v)
	})
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateTaskType() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateTaskType()
	})
}

// SetModel sets the "model" field.
func (u *LuminaTaskUpsertBulk) SetModel(v string) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateModel() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateModel()
	})
}

// SetStatus sets the "status" field.
func (u *LuminaTaskUpsertBulk) SetStatus(v string) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateStatus() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetRequestPayload sets the "request_payload" field.
func (u *LuminaTaskUpsertBulk) SetRequestPayload(v map[string]interface{}) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetRequestPayload(v)
	})
}

// UpdateRequestPayload sets the "request_payload" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateRequestPayload() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateRequestPayload()
	})
}

// SetResponsePayload sets the "response_payload" field.
func (u *LuminaTaskUpsertBulk) SetResponsePayload(v map[string]interface{}) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetResponsePayload(v)
	})
}

// UpdateResponsePayload sets the "response_payload" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateResponsePayload() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateResponsePayload()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *LuminaTaskUpsertBulk) SetErrorCode(v string) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateErrorCode() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *LuminaTaskUpsertBulk) ClearErrorCode() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *LuminaTaskUpsertBulk) SetErrorMessage(v string) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateErrorMessage() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *LuminaTaskUpsertBulk) ClearErrorMessage() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LuminaTaskUpsertBulk) SetUpdatedAt(v time.Time) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateUpdatedAt() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *LuminaTaskUpsertBulk) SetCompletedAt(v time.Time) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateCompletedAt() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *LuminaTaskUpsertBulk) ClearCompletedAt() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUserDeletedAt sets the "user_deleted_at" field.
func (u *LuminaTaskUpsertBulk) SetUserDeletedAt(v time.Time) *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.SetUserDeletedAt(v)
	})
}

// UpdateUserDeletedAt sets the "user_deleted_at" field to the value that was provided on create.
func (u *LuminaTaskUpsertBulk) UpdateUserDeletedAt() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.UpdateUserDeletedAt()
	})
}

// ClearUserDeletedAt clears the value of the "user_deleted_at" field.
func (u *LuminaTaskUpsertBulk) ClearUserDeletedAt() *LuminaTaskUpsertBulk {
	return u.Update(func(s *LuminaTaskUpsert) {
		s.ClearUserDeletedAt()
	})
}

// Exec executes the query.
func (u *LuminaTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LuminaTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LuminaTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LuminaTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
